# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kostja's github page
email: kostja@tarantool.org
description: > # this means to ignore newlines until "baseurl:"
  Random posts from 2017+. I should import my livejournal archive in 
  here someday.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kostja.github.io" # the base hostname & protocol for your site
twitter_username: kostja_osipov
github_username: kostja

# Build settings
markdown: kramdown
